---
title: "Supervised Learning"
page-layout: full

format:
    html:
        pagetitle: "Notes | Supervised Learning"
---

::: {.hidden}
$$
\def\X{{\mathcal{X}}}
\def\Y{{\mathcal{Y}}}
\def\C{{\mathcal{C}}}
\def\H{{\mathcal{H}}}
\def\D{{\mathcal{D}}}
$$
:::

## Overview

This page will go over some definitions and notation that may be seen when discussing supervised learning (though, perhaps defined more like what is seen in learning theory), as well as some basic ideas, such as classification, regression, and empirical risk minimization (ERM).

## Notation 

::: {.callout-note icon="false"}
## Definition: Instance Space

An *instance space* is a set $\X$ that contains the objects we may want to label; i.e., $\X$ is the domain of the function we want to learn.
:::

::: {.callout-note icon="false"}
## Definition: Instance

An *instance* is an element $x \in \X$. Generally, $x$ is a vector of dimension $n$; i.e., 
$$
x = (x_1, x_2, \ldots x_n).
$$

The coordinates of $x$ are called *attributes* or *features.*
:::

::: {.callout-note icon="false"}
## Definition: Label Set

A *label set* is a set $\Y$ that contains the possible labels for the objects in $\X$; i.e., $\Y$ is the codomain of the function we want to learn.

An element $y \in \Y$ is called a *label.*
:::

::: {.callout-note icon="false"}
# Definition: Example

An *example* is a labeled instance of form $(x, y) \space \text{where } x \in \X, \space y \in \Y.$
:::

::: {.callout-note icon="false"}
## Definition: Hypothesis

A *hypothesis* is a function $h : \X \rightarrow \Y$ that attempts to hypothesize (or model) how reality works, based upon the training examples given as input.

This may also be called a *predictor,* a *classifier,* or a *model.*
:::

In the supervised setting, we may assume there is some unknown function $f: \X \rightarrow \Y$ that accurately labels objects in $\X$.^[A footnote on assumptions with regards to accuracy, maybe. ] 

We want to be able to *learn* this function given only a list of training examples $S = ((x_1, y_1), \ldots (x_n, y_n)).$ So, we give a learner the list of training examples, and it outputs a hypothesis $h.$

::: {.callout-note icon="false"}
## Definition: Hypothesis Space

The *hypothesis space* $\H$ is the set of functions from which we may select one as a hypothesis.

In other words, $h \in \H.$
:::

::: {.callout-note icon="false"}
## Definition: Concept

A *concept* is a function $c : \X \rightarrow \Y$ 
:::

::: {.callout-note icon="false"}
## Definition: Concept Class

todo
:::

## Classification

todo

## Regression

todo

## Empirical Risk Minimization

todo