project:
  type: website

website:
  title: "Tiffany Le"
  site-url: https://tiffanynle.github.io/
  repo-url: https://github.com/tiffanynle/tiffanynle.github.io
  repo-actions: [edit, issue]
  page-navigation: true
  
  page-footer: 
    border: true
    background: light
    center:
      - icon: github
        href: https://github.com/tiffanynle
      - icon: envelope-fill
        href: mailto:tiffanynle.cs@gmail.com
    right: "website built with [Quarto](https://quarto.org)"
 
  navbar:
    title: false
    left:
      - text: "home"
        href: index.qmd
      - text: "notes"
        href: notes/index.qmd
      - text: "posts"
        href: posts.qmd
      - text: "projects"
        href: projects.qmd
  
  sidebar:
    - id: notes 
      title: "notes"
      style: "docked"
      pinned: true
      border: true
      collapse-level: 2
      align: left
      contents:
        - section: "Machine Learning"
          # contents: notes/machine-learning/**

format:
  html:
    theme: cosmo
    css: styles.css
