[project]
authors = ["Tiffany Le <tiffanynle.cs@gmail.com>"]
channels = ["conda-forge"]
description = "Personal website"
name = "tiffanynle.github.io"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
quarto = ">=1.6.41,<2"
jupyter = ">=1.1.1,<2"
ipython = ">=9.0.2,<10"
ipykernel = ">=6.29.5,<7"
pixi-kernel = ">=0.6.2,<0.7"
numpy = ">=2.2.3,<3"
pandas = ">=2.2.3,<3"
matplotlib = ">=3.10.1,<4"
seaborn = ">=0.13.2,<0.14"
statsmodels = ">=0.14.4,<0.15"
scikit-learn = ">=1.6.1,<2"
