---
title: "Introduction"
page-layout: full

format:
    html:
        pagetitle: "Notes | Supervised Learning | Introduction"
---

::: {.hidden}
$$
\def\X{{\mathcal{X}}}
\def\Y{{\mathcal{Y}}}
\def\C{{\mathcal{C}}}
\def\H{{\mathcal{H}}}
\def\D{{\mathcal{D}}}
\def\R{{\mathbb{R}}}
\def \E{{\mathbb{E}}}
$$
:::

## Overview

This page will go over some definitions and notation that may be seen when discussing supervised learning, as well as some other basic concepts. 

A non-trivial portion of the notes in this section (Supervised Learning) are based on lecture materials and notes from when I took [CS4033](https://www.diochnos.com/teaching/CS4033/2023S/index.php). Other references will be mentioned when appropriate.

## Notation 

::: {.callout-note icon="false"}
## Definition: Instance Space

An *instance space* is a set $\X$ that contains the objects we may want to label; i.e., $\X$ is the domain of the function we want to learn.
:::

::: {.callout-note icon="false"}
## Definition: Instance

An *instance* is an element $x \in \X$. Generally, $x$ is a vector of dimension $n$; i.e., 
$$
x = (x_1, x_2, \ldots x_n).
$$

The coordinates of $x$ are called *attributes* or *features.*
:::

::: {.callout-note icon="false"}
## Definition: Label Set

A *label set* is a set $\Y$ that contains the possible labels for the objects in $\X$; i.e., $\Y$ is the codomain of the function we want to learn.

An element $y \in \Y$ is called a *label.*
:::

::: {.callout-note icon="false"}
# Definition: Example

An *example* is a labeled instance of form $(x, y)$ where $x \in \X, \space y \in \Y.$
:::

::: {.callout-note icon="false"}
## Definition: Hypothesis

A *hypothesis* is a function $h : \X \rightarrow \Y$ that attempts to hypothesize how reality works, based upon the training examples given as input.

This may also be called a *predictor,* a *classifier,* or a *model.*
:::

::: {.callout-note icon="false"}
## Definition: Hypothesis Space

The *hypothesis space* $\H$ is the set of functions from which we may select one as a hypothesis.

In other words, $h \in \H.$
:::



::: {.callout-note icon="false"}
## Definition: Concept

A *concept* is a function $c : \X \rightarrow \Y$ that actually models reality and performs the labeling on instances in $\X$.
:::

::: {.callout-note icon="false"}
## Definition: Concept Class

The *concept class* is the class of functions $\C$ from which the concept function is coming from.

In other words, $c \in \C$.
:::

In the supervised setting, we may assume there is some unknown labeling or concept function $c$ that accurately labels instances in $\X.$ We want to be able to *learn* this function; i.e., we want to have a learner be able to produce a function $h$ that labels instances as $c$ does; i.e., $c$ is our target concept.

There are some things to note: we do not know what distribution $\D$ governs the instance space $\X$, so, we have no idea how the instances are generated; we do not have access to $\X$ itself; nor do we know the actual labeling function $c.$ (Otherwise, what is there to learn?) 

What we *do* have is a list of examples $S$: 
$$
S = ((x_1, y_1), \ldots (x_m, y_m))
$$ 

which we use to train a learner. This learner then outputs some hypothesis $h \in \H$ that may or may not accurately label new, unseen instances in $\X$ that it encounters.

 In other words, the hypothesis $h$ may or may not *generalize well.*

## Loss Functions

We have a list of examples $S,$ so we know how some specific instances $x_1, \ldots x_n \in \X^n$ are labeled. We give some of these examples to a learner, who then outputs some hypothesis $h.$ This hypothesis may or may not generalize well. We want it to. 

The question, then, is: *how can the learner learn from its mistakes?*

This is where the concept of loss (or error) and loss functions come in. **Loss functions** are of the form[^2]

$$
\ell : \Y \times \Y \rightarrow \R
$$

[^1]: Actually, there is another way to define loss functions—but that is for another time.

where it takes in two labels $(y_1, y_2)$ and outputs some penalty. The type of loss function that is used is dependent on several factors, such as the type of problem the learner is working on. 

In the supervised learning setting, there are two types of problems: **classification** and **regression.**

### Classification

For classification problems, we are attempting to predict classes; an example of this would be determining whether an image is of a dog or a cat, where "dog" and "cat" are class labels. The learner either predicts correctly, or it does not.

From this, we get the **0–1 loss** function:

$$
\ell_{0-1}(y_1, y_2) = 
\begin{cases}
1, &\text{if } y_1 \neq y_2 \\
0, &\text{if } y_1 = y_2 \\
\end{cases}
$$

Quite simply, the learner receives a penalty of 1 if it makes an incorrect prediction, and 0 if it does not; i.e., it receives no penalty.

There are other loss functions that may be used for classification, such as **cross-entropy loss** (also known as **log-loss**), which is relevant when discussing things like [logistic regression](04-logistic_regression.qmd).

### Regression

For regression problems, we are trying to predict some value in $\R,$ rather than a class label. In these cases, it would not make much sense to use 0–1 loss.

As for why, consider this: we have that, for some example $x_i,$

$$
y_i = c(x_i) = 3.0.
$$

We also have two different hypotheses $h$ and $h'$ that output
$$
h(x_i) = 2.8 \enspace \text{and} \enspace h'(x_i) = 0.4.
$$

With the 0-1 loss, both hypotheses will be given the same penalty, even though one is clearly more accurate than the other. So, rather than making the penalty dependent on whether a prediction is *exact,* we can make the penalty dependent on the *magnitude* of the error.

One option would be to take the **absolute value** of the difference:
$$
| y_1 - y_2 | = |h(x) - c(x)|
$$

Another option would be to take the **square** of the difference:
$$
(y_1 - y_2)^2 = (h(x) - c(x))^2
$$

Generally, for regression problems, we use the **square (or quadratic) loss** function:
$$
\ell_{\text{sq}}(y_1, y_2) = (y_1 - y_2)^2
$$

as this is differentiable everywhere, which is useful in some cases.

## Empirical Risk Minimization

So, for supervised learning problems we have:

- a set of examples $S = ((x_1, y_1), \ldots (x_m, y_m))$
- a hypothesis $h \in \H$
- a target concept $c \in \C$
- a loss function $\ell$

from which we need to somehow determine the quality of our hypothesis when it labels new, unseen instances in $\X.$

As a reminder, we do not know *anything* about the distribution $\D$ that governs $\X.$ We have no idea! Regardless, $h$ will predict labels for these instances $x \sim \D$, and these predictions may or may not be correct. And with every incorrect prediction, $h$ will incur some penalty.

From this, we get the idea that there is some *expected* loss that the hypothesis will suffer over the whole instance space, and the definition of **true risk** follows:

::: {.callout-note icon="false"}

# Definition: True Risk

Given a hypothesis $h \in \H,$ a concept $c \in C,$ some loss function $\ell$, and some distribution $\D,$ the *true risk* of a hypothesis is

$$
R(h, c) = \E_{x \sim \D} \space \lbrack \ell (h(x), c(x)) \rbrack
$$

This may also be known as the *generalization error* or the *true error.*
:::

We want to minimize this, but since we do not know anything about $\D,$ we have to use the *empirical risk* as a stand-in:

::: {.callout-note icon="false"}

# Definition: Empirical Risk

Given a hypothesis $h \in \H,$ a concept $c \in C,$ some loss function $\ell$, and some examples $S = ((x_1, y_1), \ldots (x_n, y_m)),$ the *empirical risk* of a hypothesis is

$$
\hat{R}(h, c) = \frac{1}{n} \sum_{i = 1}^{m} \ell (h(x_i), c(x_i))
$$
:::